# Generated by Django 6.0.4 on 2026-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course_interest', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Enrolled', 'Enrolled')], default='New', max_length=50)),
            ],
        ),
    ]
